version: '3'

services:
  account-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4001:4001"
  
  devices-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4002:4002"

  gateway-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
