version: '3'

services:
  account-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4001:4000"
  
  devices-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4002:4000"

